# ~/.dbt/profiles.yml

sep-aws-demo:
  outputs:
    dev:
      type: trino
      method: ldap
      user: starburst_service
      password: 'hc2{.71yv<b_"|Iu;,{1'
      host: sbe-official-demo-warp-speed.fieldeng.starburstdata.net  # in Starburst Galaxy: "Get Connection" -> "Host"
      port: 443
      catalog: iceberg    # the catalog in which to store transformed tables, a.k.a. dbt models
      schema: victorc_dbt  # the schema in that catalog for *your* models, separate from <dbt_yourcolleague>
      threads: 1
      http_scheme: https
      session_properties:
        query_max_run_time: 4h
  target: dev
